---
linters:
  enable:
    # By Default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Extra
    - asciicheck
    - cyclop
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - ifshort
    - lll
    - prealloc
    - revive
    - unconvert
    - whitespace
  # disable:
  #   - gosimple

issues:
  # exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  lll:
    line-length: 120
    tab-width: 4
  goimports:
    local-prefixes: github.com/arxeiss/go-expression-calculator
  golint:
    min-confidence: 0 # 0 is most strict
  cyclop:
    max-complexity: 15

# issues:
#   exclude-rules:
