---
linters:
  enable:
    # By Default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Extra
    - asciicheck
    - cyclop
    - gocritic
    - gofmt
    - goimports
    - gosec
    - ifshort
    - lll
    - prealloc
    # - revive
    - stylecheck
    - unconvert
    - whitespace
  # disable:
  #   - gosimple

issues:
  # exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  lll:
    line-length: 120
    tab-width: 4
  goimports:
    local-prefixes: github.com/arxeiss/go-expression-calculator
  cyclop:
    max-complexity: 15
  staticcheck:
    go: "1.15"
    checks: ["all", "-ST1000", "ST1003", "ST1016", "ST1020", "ST1021", "ST1022"]
  stylecheck:
    go: "1.15"
    checks: ["all", "-ST1000", "ST1003", "ST1016", "ST1020", "ST1021", "ST1022"]
  # revive:
  #   ignore-generated-header: true

# issues:
#   exclude-rules:
